"""empty message

Revision ID: 0e976c47a2e9
Revises: ba02ce7b41f0
Create Date: 2022-05-03 07:48:05.720939

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e976c47a2e9'
down_revision = 'ba02ce7b41f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('column_tableId_fkey', 'column', type_='foreignkey')
    op.create_foreign_key(None, 'column', 'table', ['tableId'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'column', type_='foreignkey')
    op.create_foreign_key('column_tableId_fkey', 'column', 'table', ['tableId'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
