"""empty message

Revision ID: 1cab1b3dd86d
Revises: d77839832d68
Create Date: 2022-04-10 22:29:12.120129

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1cab1b3dd86d'
down_revision = 'd77839832d68'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('column', 'tableId',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('column', 'tableId',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
