"""empty message

Revision ID: 52a04c6b6530
Revises: 
Create Date: 2022-05-02 07:56:00.238998

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52a04c6b6530'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('table_name_key', 'table', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('table_name_key', 'table', ['name'])
    # ### end Alembic commands ###
