"""empty message

Revision ID: 85e87b03d7fa
Revises: 1cab1b3dd86d
Create Date: 2022-04-10 22:32:15.973650

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85e87b03d7fa'
down_revision = '1cab1b3dd86d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('column_tableId_fkey', 'column', type_='foreignkey')
    op.create_foreign_key(None, 'column', 'table', ['tableId'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'column', type_='foreignkey')
    op.create_foreign_key('column_tableId_fkey', 'column', 'table', ['tableId'], ['id'])
    # ### end Alembic commands ###
