"""empty message

Revision ID: ba02ce7b41f0
Revises: d93c75369ce9
Create Date: 2022-05-02 17:55:50.645885

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ba02ce7b41f0'
down_revision = 'd93c75369ce9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cell', 'date')
    op.drop_column('cell', 'time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cell', sa.Column('time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('cell', sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
