"""empty message

Revision ID: d77839832d68
Revises: 
Create Date: 2022-04-05 10:11:13.204450

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd77839832d68'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password', sa.String(), nullable=False))
    op.drop_constraint('user_google_id_key', 'user', type_='unique')
    op.drop_column('user', 'google_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('google_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_unique_constraint('user_google_id_key', 'user', ['google_id'])
    op.drop_column('user', 'password')
    # ### end Alembic commands ###
