"""empty message

Revision ID: e2d2174830b3
Revises: 0e976c47a2e9
Create Date: 2022-05-03 09:23:41.516214

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e2d2174830b3'
down_revision = '0e976c47a2e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cell', 'currency')
    op.drop_column('cell', 'date_time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cell', sa.Column('date_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('cell', sa.Column('currency', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
